# pytorch get started

In [25]:
import numpy as np
import torch

### Tensor is the basic

In [3]:
x=torch.zeros(5,3)
print(x.size())

torch.Size([5, 3])


In [4]:
type(x.size())

torch.Size

In [6]:
x=torch.rand(5,3)

In [7]:
x

tensor([[0.0467, 0.8683, 0.8649],
        [0.2265, 0.1207, 0.0153],
        [0.2926, 0.3124, 0.7008],
        [0.3557, 0.7198, 0.2183],
        [0.8154, 0.7575, 0.9914]])

In [8]:
x[:,1]

tensor([0.8683, 0.1207, 0.3124, 0.7198, 0.7575])

### If a tensor $x$ is defined to require gradient, then any the tensor defined based on this $x$ requires 

In [38]:
x=torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [41]:
x=torch.ones(2,2,requires_grad=True)
y=torch.ones(2,2,requires_grad=False)
z=x+y
print('x', x.requires_grad)
print('y', y.requires_grad)
print('z', z.requires_grad)

x True
y False
z True


In [14]:
print(y.grad_fn)

In [15]:
z=y*y*3
out=z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [16]:
a=torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


In [17]:
out.backward()

In [18]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [19]:
x=torch.rand(3,requires_grad=True)

y=x*2
while y.data.norm()<1000:
    y=y*2
    
print(y)

tensor([491.6055, 859.5804, 987.3007], grad_fn=<MulBackward>)


In [22]:
gradients=torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
y.backward(gradients)
print(x.grad)

tensor([ 204.8000, 2048.0000,    0.2048])


In [23]:
x

tensor([0.2400, 0.4197, 0.4821], requires_grad=True)

In [24]:
x.grad

tensor([ 204.8000, 2048.0000,    0.2048])